version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 --threads 2 mysite.wsgi:application
    volumes:
      - .:/app  # Монтирование текущей директории проекта в контейнер
      - ./db.sqlite3:/app/db.sqlite3  # Монтирование файла базы данных как внешнего
      - ./staticfiles:/app/static  # Монтирование статических файлов
      - ./data:/app/data  # Папки для хранения файлов
    ports:
      - "8000:8000"  # Проброс порта для доступа к приложению
    environment:
      - SECRET_KEY=${SECRET_KEY}  # Загрузка переменной из .env
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SQLITE_DB_PATH=${SQLITE_DB_PATH}
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Конфигурация Nginx
      - ./staticfiles:/app/static  # Монтирование статических файлов
      - ./data:/app/data
    depends_on:
      - web

volumes:
  staticfiles:
  data: