# Generated by Django 5.2 on 2025-04-12 16:53

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', tinymce.models.HTMLField()),
                ('content', tinymce.models.HTMLField()),
                ('draft', models.BooleanField()),
                ('tags', models.ManyToManyField(related_name='articles', to='blog.tag')),
            ],
        ),
    ]
