# Generated by Django 5.2 on 2025-04-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_content_alter_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_title',
            field=models.CharField(default='article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
